build-osx:
	pyinstaller --name pickture --onefile --icon=files/icon.icns --windowed pickture/gui/downloader.py
build-win:
	pyinstaller --name pickture --onefile --icon=files/icon.ico --windowed pickture/gui/downloader.py
